"""Local Excel information search application."""

__version__ = "0.1.0"

from .excel_ingestion import (
    CellData,
    CellRecord,
    ExcelComReader,
    ExcelIngestion,
    ExcelReader,
    FileReadResult,
    IngestionCancelledError,
    IngestionProgress,
    IngestionResult,
    WorksheetChunk,
    WorksheetInfo,
)
from .session_index import (
    FilePreparation,
    FilePreparationService,
    FileStatus,
    IndexStore,
    IndexedCell,
    IndexedFile,
    IndexedWorksheet,
    IndexRepository,
    PreparationResult,
    SessionIndex,
    SessionIndexStore,
    SQLiteIndex,
    cleanup_stale_sessions,
)

__all__ = [
    "CellData",
    "CellRecord",
    "ExcelComReader",
    "ExcelIngestion",
    "ExcelReader",
    "FilePreparation",
    "FilePreparationService",
    "FileStatus",
    "FileReadResult",
    "IndexRepository",
    "IndexStore",
    "IndexedCell",
    "IndexedFile",
    "IndexedWorksheet",
    "IngestionCancelledError",
    "IngestionProgress",
    "IngestionResult",
    "PreparationResult",
    "SessionIndex",
    "SessionIndexStore",
    "SQLiteIndex",
    "WorksheetChunk",
    "WorksheetInfo",
    "__version__",
    "cleanup_stale_sessions",
]
