"""Local Excel information search application."""

__version__ = "0.1.0"

from .excel_ingestion import (
    CellData,
    CellRecord,
    ExcelComReader,
    ExcelIngestion,
    ExcelReader,
    FileReadResult,
    IngestionCancelledError,
    IngestionProgress,
    IngestionResult,
    WorksheetChunk,
    WorksheetInfo,
)
from .exporter import (
    ExcelComExporter, ExportCancelledError, ExportError, ExportProgress, ExportResult, ExportService, ExportSnapshot,
    cleanup_stale_exports,
)
from .search_engine import (
    FormulaMode,
    MatchMode,
    SearchEngine,
    SearchError,
    SearchOperator,
    SearchPage,
    SearchResult,
    SearchService,
    normalize_display_value,
    normalize_value,
)

from .export_fidelity import ExportFidelitySpike, ExportMode, ExportResult as FidelityExportResult, ExportRow
from .hardening import ClassifiedError, ErrorCategory, TaskCoordinator, TaskState, classify_error

from .session_index import (
    FilePreparation,
    FilePreparationService,
    FileStatus,
    IndexStore,
    IndexedCell,
    IndexedFile,
    IndexedWorksheet,
    IndexRepository,
    PreparationResult,
    SessionIndex,
    SessionIndexStore,
    SQLiteIndex,
    cleanup_stale_sessions,
)

__all__ = [
    "CellData",
    "CellRecord",
    "ExcelComReader",
    "ExcelIngestion",
    "ExcelReader",
    "FilePreparation",
    "FilePreparationService",
    "FileStatus",
    "FileReadResult",
    "IndexRepository",
    "IndexStore",
    "IndexedCell",
    "IndexedFile",
    "IndexedWorksheet",
    "IngestionCancelledError",
    "IngestionProgress",
    "IngestionResult",
    "PreparationResult",
    "SessionIndex",
    "SessionIndexStore",
    "SQLiteIndex",
    "WorksheetChunk",
    "WorksheetInfo",
    "__version__",
    "cleanup_stale_sessions",
    "ExportFidelitySpike",
    "ExportMode",
    "FidelityExportResult",
    "ExportRow",
    "ExcelComExporter",
    "ExportCancelledError",
    "ExportError",
    "ExportProgress",
    "ExportResult",
    "ExportService",
    "ExportSnapshot",
    "cleanup_stale_exports",
    "FormulaMode",
    "MatchMode",
    "SearchEngine",
    "SearchError",
    "SearchOperator",
    "SearchPage",
    "SearchResult",
    "SearchService",
    "normalize_display_value",
    "normalize_value",
    "ClassifiedError",
    "ErrorCategory",
    "TaskCoordinator",
    "TaskState",
    "classify_error",
]
